In [13]:
import numpy as np

In [14]:
matrix = np.zeros((4,4,4,5))

In [15]:
test = matrix[2,2]
test

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
test.argmax()

0

In [17]:
test.argmax(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [18]:
test.argmax(axis=0)

array([0, 0, 0, 0, 0], dtype=int64)

In [23]:
np.where(test==np.amax(test))

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       dtype=int64))

In [22]:
test.size

20