In [24]:
import numpy as np

In [26]:
matrix = np.random.rand(4,4,4,5)

In [27]:
test = matrix[2,2]
test

array([[0.44002826, 0.03876385, 0.12645063, 0.07591542, 0.36990607],
       [0.3080993 , 0.62441405, 0.93692616, 0.66350461, 0.41335061],
       [0.78460591, 0.23113245, 0.96468721, 0.65876485, 0.44314057],
       [0.68957409, 0.3078669 , 0.65866752, 0.37896667, 0.41917382]])

In [28]:
test.argmax()

12

In [29]:
test.argmax(axis=1)

array([0, 2, 2, 0], dtype=int64)

In [30]:
test.argmax(axis=0)

array([2, 1, 2, 1, 2], dtype=int64)

In [ ]:
ind = np.where(test==np.amax(test))

In [ ]:
test.size

20

In [ ]:
def epsilon_greedy(state_1, state_2, q_func, epsilon):
    """Returns an action selected by an epsilon-Greedy exploration policy

    Args:
        state_1, state_2 (int, int): two indices describing the current state
        q_func (np.ndarray): current Q-function
        epsilon (float): the probability of choosing a random command

    Returns:
        (int, int): the indices describing the action/object to take
    """
    # TODO Your code here  
    action_index, object_index = 0,0
    prob = np.random.random()
    print(prob)
    if prob < epsilon:
        rand_act = np.random.randint(4)
        rand_obj = np.random.randint(4)
        action_index, object_index = rand_act, rand_obj
    else:
        max_index = np.where(q_func[state_1,state_2]==np.amax(q_func[state_1,state_2]))
        print(max_index)
        action_index = max_index[0][0]
        object_index = max_index[1][0]
    return (action_index, object_index)

In [ ]:
epsilon_greedy(1,1,matrix, 0.3)

0.8869892685196831
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
      dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
      dtype=int64))


(0, 0)

In [ ]:
def index2tuple(index):
    """Converts an index c to a tuple (a,b)"""
    return index // NUM_OBJECTS, index % NUM_OBJECTS

In [ ]:
ind[1][0]

0

In [ ]:
index2tuple(ind)

TypeError: unsupported operand type(s) for //: 'tuple' and 'int'

In [ ]:
def tuple2index(action_index, object_index):
    """Converts a tuple (a,b) to an index c"""
    return action_index * NUM_OBJECTS + object_index

0