In [1]:
import numpy as np

In [3]:
(np.maximum(0,3))

3

In [27]:
def rectified_linear_unit(x):
    """ Returns the ReLU of x, or the maximum between 0 and x."""
    return(np.maximum(0,x))

In [29]:
vecmax = np.vectorize(rectified_linear_unit)

In [31]:
vecmax([1,-2,3,-4,5,-6,7])

array([1, 0, 3, 0, 5, 0, 7])

In [42]:
x = np.array([[1],[2]])
y = np.array([[1, 2],[3, 4],[5, 6]])

In [46]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.dot(x.T,np.)

array([[ 5, 11, 17]])