In [34]:
import numpy as np
from numpy import random

In [35]:
def hinge_loss_single(feature_vector, label, theta, theta_0):
    """
    Finds the hinge loss on a single data point given specific classification
    parameters.

    Args:
        feature_vector - A numpy array describing the given data point.
        label - A real valued number, the correct classification of the data
            point.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given data point and parameters.
    """
    # Your code here
    z = label*(np.matmul(theta, feature_vector) + theta_0)
    hinge = np.max([0, 1-z])
    return hinge
    raise NotImplementedError

In [36]:
fv= np.array([0.55500015, 0.22262817, 0.46742575, 0.07716229, 0.48056357, 0.73576736,
 0.72758698, 0.29723448, 0.05111963, 0.92799158])
label= -1.0
theta= np.array([0.09009007, 0.22458973, 0.10696886, 0.64798494, 0.10404451, 0.06795626,
 0.06872031, 0.16821736, 0.97809792, 0.0538798])
theta_0= 0.5

In [37]:
hinge_loss_single(fv,label,theta,theta_0)

2.0000000104528266

In [38]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    # Your code here
    out = np.array([hinge_loss_single(x, y, theta, theta_0) for x,y in zip(feature_matrix, labels)])
    loss = out.mean()
    return loss
    raise NotImplementedError

In [39]:
fb = np.stack((fv,fv))
labels = [-1.0, -1.0]

In [40]:
hinge_loss_full(fb, labels, theta, theta_0)

2.0000000104528266

In [41]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    if label * (np.dot(current_theta, feature_vector) + current_theta_0) <= 0:
        current_theta += label * feature_vector
        current_theta_0 += label
    return (current_theta, current_theta_0)
    raise NotImplementedError


In [42]:
data = {'feature_vector': [-0.10017974 ,-0.40336822, -0.1594446,  -0.26484401, -0.27174761,  0.12395215,
  0.15144639, -0.25479186,  0.28601179,  0.27694616],
'label': -1,
'theta': [ 0.13112945,  0.28012299,  0.36195576, -0.21725298, -0.44001617, -0.20251099,
  0.47820471,  0.00530194, -0.3212308,   0.003165  ],
'theta_0': -0.5531564570019423}

In [43]:
test = np.zeros((10,2))

In [44]:
test.shape[1]

2

In [45]:
words = list(open('../Scripts/project1/sentiment_analysis/stopwords.txt').readlines())

In [46]:
words2 = list(map(str.strip, words))

In [47]:
words2 

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 'her',
 'hers',
 'herself',
 'it',
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 '

In [48]:
words3 = words2 + ['test', 'this', 'thing']

In [49]:
wordlist_clean = [word for word in words3 if word not in words2]

In [50]:
wordlist_clean

['test', 'thing']

In [51]:

def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indices = list(range(n_samples))
        random.shuffle(indices)
        return indices

In [52]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    # Your code here
    theta = np.zeros(feature_matrix.shape[1],)
    theta_0 = 0
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            # Your code here
            theta, theta_0 = perceptron_single_step_update(feature_matrix[i], labels[i], theta, theta_0)
            pass
    return theta, theta_0
    raise NotImplementedError

In [62]:
data = np.array([(0,0)	,(2,0)	,(3,0)	,(0,2),	(2,2),	(5,1),	(5,2)	,(2,4),	(4,4)])
labels = np.array([-1,-1,-1	,-1	,-1	,1,1,1	,1])

In [61]:
perceptron(data, labels, 12)

(array([5., 5.]), -10)

In [63]:
from sklearn.svm import LinearSVC


### Functions for you to fill in ###

def one_vs_rest_svm(train_x, train_y, test_x):
    """
    Trains a linear SVM for binary classifciation

    Args:
        train_x - (n, d) NumPy array (n datapoints each with d features)
        train_y - (n, ) NumPy array containing the labels (0 or 1) for each training data point
        test_x - (m, d) NumPy array (m datapoints each with d features)
    Returns:
        pred_test_y - (m,) NumPy array containing the labels (0 or 1) for each test data point
    """
    LSVC = LinearSVC(random_state=0, C=0.1)
    LSVC.fit(train_x, train_y)
    pred_test_y = LSVC.predict(test_x)
    return pred_test_y
    raise NotImplementedError

In [68]:
test = np.array([5,5])
data

array([[0, 0],
       [2, 0],
       [3, 0],
       [0, 2],
       [2, 2],
       [5, 1],
       [5, 2],
       [2, 4],
       [4, 4]])

In [71]:
result = one_vs_rest_svm(data, labels, test.reshape(1,-1))

In [72]:
result

array([1])